import os
API_ID = int(os.environ.get("API_ID", ""))
API_HASH = os.environ.get("API_HASH", "") 
BOT_TOKEN = os.environ.get("BOT_TOKEN", "") 
OPENAI_KEY = os.environ.get("OPENAI_KEY","")
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"") 
SUDO=os.environ.get("SUDO","5910057231")
BOT_NAME = os.environ.get("BOT_NAME","")
START_IMG = os.environ.get("START_IMG","https://te.legra.ph/file/9fa2101b77407dbec7d31.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS","")
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","")
OWNER_USERNAME = os.environ.get("OWNER_USERNAME","")
SUDO=os.environ.get("SUDO","5910057231")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","")
BARD_TOKEN=os.environ.get("BARD_TOKEN","")
